// ==========================================
// PHOTO GALLERY CONFIGURATION
// Auto-generated from images/gallery/ folder
// Run ./update-gallery.sh to refresh
// Last updated: 2026-01-02 14:04:22
// ==========================================

const GALLERY_CONFIG = {
  // Show/hide gallery section
  // Set to false to hide gallery even if photos exist
  showGallery: false,

  // Photo list (auto-generated by script)
  photos: [
    "images/gallery/VANH7500_1aV.jpg",
    "images/gallery/VANH7514_1aV.jpg",
    "images/gallery/VANH7524_1a.jpg",
    "images/gallery/VANH7553_1aV.jpg",
    "images/gallery/VANH7577_1aa.jpg",
    "images/gallery/VANH7602_1aa.jpg",
    "images/gallery/VANH7615_1aa.jpg",
    "images/gallery/VANH7674_1aa.jpg",
    "images/gallery/VANH8371_1aV.jpg",
    "images/gallery/VANH8386_1aV.jpg",
    "images/gallery/VANH8405_1a.jpg",
    "images/gallery/VANH8449_1aVB.jpg",
    "images/gallery/VANH8487_1a.jpg",
    "images/gallery/VANH8500_1aV.jpg",
    "images/gallery/VANH8548_1a.jpg",
    "images/gallery/VANH8554_1aV.jpg"
  ]
};

// Make config available globally
window.GALLERY_CONFIG = GALLERY_CONFIG;
