// ==========================================
// PHOTO GALLERY CONFIGURATION
// Auto-generated from images/gallery/ folder
// Run ./update-gallery.sh to refresh
// Last updated: 2026-01-02 20:23:43
// ==========================================

const GALLERY_CONFIG = {
  // Show/hide gallery section
  // Set to false to hide gallery even if photos exist
  showGallery: true,

  // Photo list (auto-generated by script)
  photos: [
    "images/gallery/VANH7500_1aV-min.jpg",
    "images/gallery/VANH7514_1aV-min.jpg",
    "images/gallery/VANH7553_1aV-min.jpg",
    "images/gallery/VANH7602_1aa-min.jpg",
    "images/gallery/VANH7615_1aa-min.jpg",
    "images/gallery/VANH8386_1aV-min.jpg",
    "images/gallery/VANH8430_1aCV-min.jpg",
    "images/gallery/VANH8449_1aVB-min.jpg",
    "images/gallery/VANH8500_1aV-min.jpg"
  ]
};

// Make config available globally
window.GALLERY_CONFIG = GALLERY_CONFIG;
