#!/bin/bash

# ============================================
# AUTO-UPDATE GALLERY PHOTOS
# Tự động cập nhật danh sách ảnh gallery
# Chỉ update file gallery-config.js (không động đến config.js)
# ============================================

GALLERY_FOLDER="images/gallery"
GALLERY_CONFIG="gallery-config.js"

echo "🖼️  Scanning gallery folder: $GALLERY_FOLDER"

# Read current showGallery setting if config exists
SHOW_GALLERY="true"
if [ -f "$GALLERY_CONFIG" ]; then
    # Extract current showGallery value
    CURRENT_SHOW=$(grep "showGallery:" "$GALLERY_CONFIG" | sed 's/.*showGallery: *\([^,]*\).*/\1/')
    if [ ! -z "$CURRENT_SHOW" ]; then
        SHOW_GALLERY="$CURRENT_SHOW"
    fi
fi

# Check if gallery folder exists
if [ ! -d "$GALLERY_FOLDER" ]; then
    echo "❌ Gallery folder not found: $GALLERY_FOLDER"
    echo "Creating empty gallery-config.js..."

    cat > "$GALLERY_CONFIG" << EOF
// ==========================================
// PHOTO GALLERY CONFIGURATION
// Auto-generated from images/gallery/ folder
// Run ./update-gallery.sh to refresh
// ==========================================

const GALLERY_CONFIG = {
  // Show/hide gallery section
  // Set to false to hide gallery even if photos exist
  showGallery: $SHOW_GALLERY,

  // Photo list (auto-generated by script)
  photos: []
};

// Make config available globally
window.GALLERY_CONFIG = GALLERY_CONFIG;
EOF

    echo "✅ Created empty gallery config"
    exit 0
fi

# Get all image files, sorted by name
PHOTOS=$(find "$GALLERY_FOLDER" -type f \
    \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" -o -iname "*.gif" \) \
    | sort \
    | sed 's|^|    "|' \
    | sed 's|$|",|')

# Count photos
PHOTO_COUNT=$(echo "$PHOTOS" | wc -l | tr -d ' ')

# Check if no photos found
if [ -z "$PHOTOS" ] || [ "$PHOTO_COUNT" -eq 0 ]; then
    echo "⚠️  No photos found in $GALLERY_FOLDER"
    echo "Creating empty gallery-config.js..."

    cat > "$GALLERY_CONFIG" << EOF
// ==========================================
// PHOTO GALLERY CONFIGURATION
// Auto-generated from images/gallery/ folder
// Run ./update-gallery.sh to refresh
// ==========================================

const GALLERY_CONFIG = {
  // Show/hide gallery section
  // Set to false to hide gallery even if photos exist
  showGallery: $SHOW_GALLERY,

  // Photo list (auto-generated by script)
  photos: []
};

// Make config available globally
window.GALLERY_CONFIG = GALLERY_CONFIG;
EOF

    echo "✅ Created empty gallery config (gallery will be hidden)"
    exit 0
fi

echo "📸 Found $PHOTO_COUNT photos"

# Remove trailing comma from last photo
PHOTOS=$(echo "$PHOTOS" | sed '$ s/,$//')

# Backup old config if exists
if [ -f "$GALLERY_CONFIG" ]; then
    cp "$GALLERY_CONFIG" "${GALLERY_CONFIG}.backup"
    echo "💾 Backed up old gallery config to ${GALLERY_CONFIG}.backup"
fi

# Create new gallery-config.js
cat > "$GALLERY_CONFIG" << EOF
// ==========================================
// PHOTO GALLERY CONFIGURATION
// Auto-generated from images/gallery/ folder
// Run ./update-gallery.sh to refresh
// Last updated: $(date '+%Y-%m-%d %H:%M:%S')
// ==========================================

const GALLERY_CONFIG = {
  // Show/hide gallery section
  // Set to false to hide gallery even if photos exist
  showGallery: $SHOW_GALLERY,

  // Photo list (auto-generated by script)
  photos: [
$PHOTOS
  ]
};

// Make config available globally
window.GALLERY_CONFIG = GALLERY_CONFIG;
EOF

echo "✅ Gallery updated successfully!"
echo "📊 Total photos: $PHOTO_COUNT"
echo ""
echo "Gallery config updated in gallery-config.js"
echo "Refresh your browser to see the changes."
